### ISSUE TITLE
wavelglow的配置要求？

### ISSUE THREAD

**Issue by CarolinGao** [lingjzhu/probing-TTS-models#1]
你好!
我生成了一些语谱图（不是用troco2），然后把它们feed进waveglow模型无法合成声音，出来的都是噪音。但是我用Griffin-Lim这种传统声码器可以合成声音。waveglow对声谱图有什么要求吗？我已经把hop_len对齐了。谢谢！
https://colab.research.google.com/drive/1bTdnNdsmZE-TAae5bSzBlAUx81RKsPcP?usp=sharing

**Comment by lingjzhu** [comment]
> 你好!
> 我生成了一些语谱图（不是用troco2），然后把它们feed进waveglow模型无法合成声音，出来的都是噪音。但是我用Griffin-Lim这种传统声码器可以合成声音。waveglow对声谱图有什么要求吗？我已经把hop_len对齐了。谢谢！
> https://colab.research.google.com/drive/1bTdnNdsmZE-TAae5bSzBlAUx81RKsPcP?usp=sharing

Griffin-Lim是一个通用的方法，可以合成任何人的声音。但是waveglow这类声码器是针对特定的说话人训练的，要是换了一个人的声音，或者换了与谱图的参数，就只能生成噪音了。

**Comment by CarolinGao** [comment]
> > 你好!
> > 我生成了一些语谱图（不是用troco2），然后把它们feed进waveglow模型无法合成声音，出来的都是噪音。但是我用Griffin-Lim这种传统声码器可以合成声音。waveglow对声谱图有什么要求吗？我已经把hop_len对齐了。谢谢！
> > https://colab.research.google.com/drive/1bTdnNdsmZE-TAae5bSzBlAUx81RKsPcP?usp=sharing
> 
> Griffin-Lim是一个通用的方法，可以合成任何人的声音。但是waveglow这类声码器是针对特定的说话人训练的，要是换了一个人的声音，或者换了与谱图的参数，就只能生成噪音了。

我了解了一下目前比较好vocoder对声谱图的hop_length要求都是256，请问你知道为啥要设置成256吗？如果我改成192，重新训练可以吗？我看到melgan的作者在代码中注释这个值不能改。

**Comment by lingjzhu** [comment]
> > > 你好!
> > > 我生成了一些语谱图（不是用troco2），然后把它们feed进waveglow模型无法合成声音，出来的都是噪音。但是我用Griffin-Lim这种传统声码器可以合成声音。waveglow对声谱图有什么要求吗？我已经把hop_len对齐了。谢谢！
> > > https://colab.research.google.com/drive/1bTdnNdsmZE-TAae5bSzBlAUx81RKsPcP?usp=sharing
> > 
> > 
> > Griffin-Lim是一个通用的方法，可以合成任何人的声音。但是waveglow这类声码器是针对特定的说话人训练的，要是换了一个人的声音，或者换了与谱图的参数，就只能生成噪音了。
> 
> 我了解了一下目前比较好vocoder对声谱图的hop_length要求都是256，请问你知道为啥要设置成256吗？如果我改成192，重新训练可以吗？我看到melgan的作者在代码中注释这个值不能改。

一般情况下hop_length都会设置成2的幂，256和512都是常用的值。有什么特定的原因要用192吗？vocoder的设置要和语音合成模型的输出一致，不然就无法生成正常语音。
