### ISSUE TITLE
提取bert embedding训练疑问

### ISSUE THREAD

**Issue by wenbo1188** [lingjzhu/probing-TTS-models#2]
你好，我发现在训练前的预处理部分提取bert embedding的代码中，并没有去除隐状态h中的头部和尾部的token的表示，但在inference_bert.ipynb中提取bert embedding的代码中包含了去除相应token的h[:, 1:-1, :]操作，请问你在训练时候是和合成时有区别，还是一致的呢

**Comment by lingjzhu** [comment]
啊你很细心，是一致的。预训练代码一年前的，跟colab用了不同版本的transformers。transformers之前的一个版本输出隐状态不是默认的，需要选个argument。等到写colab的时候更新出来了，所以就修改了colab的版本。h头部和尾部的token会影响hidden vector和拼音的对齐，所以当初没有加上。

**Comment by wenbo1188** [comment]
好的，多谢
