### ISSUE TITLE
some problem when run own model

### ISSUE THREAD

**Issue by ccuiyuhan** [lingjzhu/probing-TTS-models#4]
你好，我在用自己训练的的模型合成语音时，遇到了下面的错误：
Traceback (most recent call last):
  File "D:/cuiyuhan/PycharmWorkplace/text-to-speech/probing-TTS-models-master/synthesize.py", line 142, in <module>
    model.load_state_dict(torch.load(checkpoint_path))
  File "D:\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron2:
	Missing key(s) in state_dict: "embedding.weight", "encoder.convolutions.0.0.conv.weight", "encoder.convolutions.0.0.conv.bias", "encoder.convolutions.0.1.weight", "encoder.convolutions.0.1.bias", "encoder.convolutions.0.1.running_mean", "encoder.convolutions.0.1.running_var", "encoder.convolutions.1.0.conv.weight", "encoder.convolutions.1.0.conv.bias", "encoder.convolutions.1.1.weight", "encoder.convolutions.1.1.bias", "encoder.convolutions.1.1.running_mean", "encoder.convolutions.1.1.running_var", "encoder.convolutions.2.0.conv.weight", "encoder.convolutions.2.0.conv.bias", "encoder.convolutions.2.1.weight", "encoder.convolutions.2.1.bias", "encoder.convolutions.2.1.running_mean", "encoder.convolutions.2.1.running_var", "encoder.lstm.weight_ih_l0", "encoder.lstm.weight_hh_l0", "encoder.lstm.bias_ih_l0", "encoder.lstm.bias_hh_l0", "encoder.lstm.weight_ih_l0_reverse", "encoder.lstm.weight_hh_l0_reverse", "encoder.lstm.bias_ih_l0_reverse", "encoder.lstm.bias_hh_l0_reverse", "decoder.prenet.layers.0.linear_layer.weight", "decoder.prenet.layers.1.linear_layer.weight", "decoder.attention_rnn.weight_ih", "decoder.attention_rnn.weight_hh", "decoder.attention_rnn.bias_ih", "decoder.attention_rnn.bias_hh", "decoder.attention_layer.query_layer.linear_layer.weight", "decoder.attention_layer.memory_layer.linear_layer.weight", "decoder.attention_layer.v.linear_layer.weight", "decoder.attention_layer.location_layer.location_conv.conv.weight", "decoder.attention_layer.location_layer.location_dense.linear_layer.weight", "decoder.decoder_rnn.weight_ih", "decoder.decoder_rnn.weight_hh", "decoder.decoder_rnn.bias_ih", "decoder.decoder_rnn.bias_hh", "decoder.linear_projection.linear_layer.weight", "decoder.linear_projection.linear_layer.bias", "decoder.gate_layer.linear_layer.weight", "decoder.gate_layer.linear_layer.bias", "postnet.convolutions.0.0.conv.weight", "postnet.convolutions.0.0.conv.bias", "postnet.convolutions.0.1.weight", "postnet.convolutions.0.1.bias", "postnet.convolutions.0.1.running_mean", "postnet.convolutions.0.1.running_var", "postnet.convolutions.1.0.conv.weight", "postnet.convolutions.1.0.conv.bias", "postnet.convolutions.1.1.weight", "postnet.convolutions.1.1.bias", "postnet.convolutions.1.1.running_mean", "postnet.convolutions.1.1.running_var", "postnet.convolutions.2.0.conv.weight", "postnet.convolutions.2.0.conv.bias", "postnet.convolutions.2.1.weight", "postnet.convolutions.2.1.bias", "postnet.convolutions.2.1.running_mean", "postnet.convolutions.2.1.running_var", "postnet.convolutions.3.0.conv.weight", "postnet.convolutions.3.0.conv.bias", "postnet.convolutions.3.1.weight", "postnet.convolutions.3.1.bias", "postnet.convolutions.3.1.running_mean", "postnet.convolutions.3.1.running_var", "postnet.convolutions.4.0.conv.weight", "postnet.convolutions.4.0.conv.bias", "postnet.convolutions.4.1.weight", "postnet.convolutions.4.1.bias", "postnet.convolutions.4.1.running_mean", "postnet.convolutions.4.1.running_var". 
	Unexpected key(s) in state_dict: "iteration", "state_dict", "optimizer", "learning_rate". 

Process finished with exit code 1

初学者，不知道该如何解决，感谢解答！

**Comment by lingjzhu** [comment]
Hi, it seems that the model does not match the code. The code is compatible with two different versions of models, with BERT or without BERT. If you select the correct argument flyer, this should be solved. You can also refer to the colab to debug.

**Comment by ccuiyuhan** [comment]
> Hi, it seems that the model does not match the code. The code is compatible with two different versions of models, with BERT or without BERT. If you select the correct argument flyer, this should be solved. You can also refer to the colab to debug.

Thanks for replying，the model named Tacotron2 trained by yourself is the model withour BERT？i use your model（Tacotron2）can work.

**Comment by ccuiyuhan** [comment]
> Hi, it seems that the model does not match the code. The code is compatible with two different versions of models, with BERT or without BERT. If you select the correct argument flyer, this should be solved. You can also refer to the colab to debug.

sorry for bothering again，when i use your trained model（Tacotron2）as a a pre-trained model to run trian.py, i met:

Traceback (most recent call last):
  File "D:/cuiyuhan/PycharmWorkplace/text-to-speech/probing-TTS-models-master/train.py", line 308, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "D:/cuiyuhan/PycharmWorkplace/text-to-speech/probing-TTS-models-master/train.py", line 206, in train
    checkpoint_path, model, optimizer)
  File "D:/cuiyuhan/PycharmWorkplace/text-to-speech/probing-TTS-models-master/train.py", line 110, in load_checkpoint
    model.load_state_dict(checkpoint_dict['state_dict'])
KeyError: 'state_dict'
the format of  the saved model  seems different from the loaded mode

**Comment by lingjzhu** [comment]
I see. That's a problem. Could you use torch.load() to load the saved model and to examine if the key "state_dict" is there?
You can try to rewrite this function with torch.load().

Undoubtedly, there are bugs primarily caused by mismatched versions of various packages, as the development and release of this project have spanned a long time. I am thinking of fixing them but do not have time to do this currently. Take a look at [Espnet](https://github.com/espnet/espnet), which is more robust and has more up-to-date models.

**Comment by ccuiyuhan** [comment]
> I see. That's a problem. Could you use torch.load() to load the saved model and to examine if the key "state_dict" is there?
> You can try to rewrite this function with torch.load().

thanks，if i use torch.load(checkpoint_path))['state_dict']，it doesn‘t work for  your trained model(Tacotron2).also,there doesn't exsit key 'optimizer','learning_rate' and 'iteration',but it worked for my own model.The model I trained by myself didn't work well，so i want to use your model to finetune.

**Comment by lingjzhu** [comment]
> > I see. That's a problem. Could you use torch.load() to load the saved model and to examine if the key "state_dict" is there?
> > You can try to rewrite this function with torch.load().
> 
> thanks，if i use torch.load(checkpoint_path))['state_dict']，it doesn‘t work for your trained model(Tacotron2).also,there doesn't exsit key 'optimizer','learning_rate' and 'iteration',but it worked for my own model.The model I trained by myself didn't work well，so i want to use your model to finetune.

Now I know why. When I release the model, I have removed other keys as they inflate the total size of the model, which may, unfortunately, contribute to your trouble. Thanks for your interest in this project. 
If you are serious about TTS, I guess Espnet will be a great choice.

**Comment by ccuiyuhan** [comment]
Thank you for your patience！I will refer to it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lingjzhu/probing-TTS-models"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 晚上10:01
收件人:&nbsp;"lingjzhu/probing-TTS-models"<probing-TTS-models@noreply.github.com&gt;;
抄送:&nbsp;"崔宇涵"<937903992@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lingjzhu/probing-TTS-models] some problem when run own model (#4)





   
I see. That's a problem. Could you use torch.load() to load the saved model and to examine if the key "state_dict" is there?
 You can try to rewrite this function with torch.load().
  
thanks，if i use torch.load(checkpoint_path))['state_dict']，it doesn‘t work for your trained model(Tacotron2).also,there doesn't exsit key 'optimizer','learning_rate' and 'iteration',but it worked for my own model.The model I trained by myself didn't work well，so i want to use your model to finetune.
  
Now I know why. When I release the model, I have removed other keys as they inflate the total size of the model, which may, unfortunately, contribute to your trouble. Thanks for your interest in this project.
 If you are serious about TTS, I guess Espnet will be a great choice.
